### ISSUE TITLE
Undefined Method 'Encode' Error

### ISSUE THREAD

**Issue by JoshSinyor** [aterris/simplecov-shield#6]
I'm encountering an error when trying to use this gem with Ruby 3.0, which I think is due to the absence of the `URI.escape` method from Ruby 3.0.  `URI.escape` was apparently deprecated a long time ago and removed from Ruby 3.0 entirely. The error I receive:

```
/Users/usr/.rvm/gems/ruby-3.0.0/gems/simplecov-shield-0.0.3/lib/simplecov-shield.rb:32:in `shield_url': undefined method `encode' for URI:Module (NoMethodError)
        from /Users/usr/.rvm/gems/ruby-3.0.0/gems/simplecov-shield-0.0.3/lib/simplecov-shield.rb:24:in `block in generate_shield'
        from /Users/usr/.rvm/gems/ruby-3.0.0/gems/simplecov-shield-0.0.3/lib/simplecov-shield.rb:23:in `open'
        from /Users/usr/.rvm/gems/ruby-3.0.0/gems/simplecov-shield-0.0.3/lib/simplecov-shield.rb:23:in `generate_shield'
        from /Users/usr/.rvm/gems/ruby-3.0.0/gems/simplecov-shield-0.0.3/lib/simplecov-shield.rb:19:in `format'
        from /Users/usr/.rvm/gems/ruby-3.0.0/gems/simplecov-0.8.2/lib/simplecov/result.rb:46:in `format!'
        from /Users/usr/.rvm/gems/ruby-3.0.0/gems/simplecov-0.8.2/lib/simplecov/configuration.rb:139:in `block in at_exit'
        from /Users/usr/.rvm/gems/ruby-3.0.0/gems/simplecov-0.8.2/lib/simplecov/defaults.rb:54:in `block in <top (required)>'
```

Are you still working on this gem?

Environment:
- Ruby 3.0.0
- RSpec 3.10.0
- SimpleCov 0.8.2
- SimpleCov Console 0.9.1
- SimpleCov Shield 0.0.3

**Comment by JoshSinyor** [comment]
Resolved by [Pull Request 7](https://github.com/aterris/simplecov-shield/pull/7).
